# We are using the iOS build system to create Mac OS X python builds
language: python
pytnon:
  - "3.5"

os:
#  - osx
  - linux

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron
    - pip
    - $HOME/.cache/our-brew

before_install:
  - ./scripts/travis.sh pre-install

install:
  - ./scripts/travis.sh install

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: ot-app-builds
  skip_cleanup: true
  local-dir: releases
  upload-dir: mac
  acl: public_read
  on:
    repo: OpenTrons/opentrons-app
    all_branches: true

notifications:
  email:
    on_success: change
    on_failure: change
