sudo: false
language: python
python:
- '3.4'
before_install:
- openssl aes-256-cbc -K $encrypted_f176ff9ac49f_key -iv $encrypted_f176ff9ac49f_iv -in .pypirc.enc -out $HOME/.pypirc -d
install:
  - python setup.py install
  - pip install -r requirements.txt
script:
- nosetests --with-coverage
- pylama
- cd docs && make html && cd ..
- cd scripts && ./doc-deploy.sh && cd ..
deploy:
  provider: script
  skip_cleanup: true
  script: python setup.py sdist bdist_wheel && twine upload dist/*
  on:
    tags: true
env:
  global:
  - ENCRYPTION_LABEL: c6cefc96bb2c
  - COMMIT_AUTHOR_EMAIL: sphinx@opentrons.com
after_success: coveralls


