sudo: false
language: python
python:
- '3.4'
before_install:
- openssl aes-256-cbc -K $encrypted_f176ff9ac49f_key -iv $encrypted_f176ff9ac49f_iv -in .pypirc.enc -out $HOME/.pypirc -d
install:
- python setup.py install
- pip install pylama
- pip install coverage
- pip install coveralls
- pip install Sphinx==1.4.8
- pip install numpydoc==0.6.0
script:
- nosetests --with-coverage
- pylama
- cd docs && make html && cd ..
- cd scripts && ./doc-deploy.sh && cd ..
- python setup.py sdist bdist_wheel
deploy:
  provider: script
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  on:
    tags: true
env:
  global:
  - ENCRYPTION_LABEL: c6cefc96bb2c
  - COMMIT_AUTHOR_EMAIL: sphinx@opentrons.com
  - secure: XLgpfbqKB7KDN9tPzaeB0DSUnZfeXquM1MbXMlVlVqvBdSVSQRWR1fw8hfRbwzBI/cm8eMJdQOSHAZFcEVkh8fSqNfi+pL5FcCPYrKAJBbzt7SzNBWo2dBVR4k3Dt5LB1AbPLKmwpuPSxjFzO8SamLbG3kQ19Z7FIjtiOFbSxN3ctS1AdjlFgMJxUF9qYe273Jp1bHjScMASiPwO0BsPUH72pVTIGE7lTJBqShalCtje+WgJGsg390ZTfBEIx/MYfwl8+jhttB7NqhybGZhLwVAsgRMEte6jt7Ex8cCbRRpV+jokVNAU6L0OMxgHhFYgrt1YyX/dgtIoPXwAIxZNRc5vJuWAx73UnQy+Zd36PBB65E68fZJa4Iz1CXleciqymr/v+Q4m/My8n6E2C8XEVdpgZYaFH/CjdZ1ctIx5Kv5yhQzdO4gBMJcDBFyt1dCOvRW+rDH/VnkQpIQJ+mtTHkXpaAXczpk0oPIIbVoSJXpTe5r9VZLO4bfbCyfrSlEPUU2Kp+jDZguZ6+1UpZXtDQU85ANdyoKh8lQr4iI0OR0BlirTcY7ljtcjc5gM5RRY1/3LO1zEiDUJ47+13vUv4YO/JANiTeDcgt/wkaQpxFjPTvX7xWuQYQY1O1VjGF7fBlD9N6Vi/Ef/aS7h3Sol2V4xgujmQux9oFcZSZCV1+Y=
  - secure: SJCEbV7qKGNu+Doadmz4JKc9+R59CnPWr5gGuWw59AmL4HiUxmDGibz63mSytLEIKmeaxAQMsfk5fPFbxI8POHr6aWTH6Boep4bfenhcZ0CdqATzWc7G0OkaszOjsQTqfKvg0Z1YGTHtdEetIXa7A/ABjqg00rdBsAaSTDSkgaHnqtV2q/Ta7gsQndEOk+s3nj5UjXVhNubtlvX9XS91IJbKWefnjZDEfcHB6xpkbm4uLXBQiLiWLVnt5SIXvE11LHuBzz85eMKDBOLcl6HUF3C48u+ZN7RgjeFzjIr+dQNedl76lpSNkyR+eP+iUN45CwCNgT/h0qs2C+8C6uUSK6AwoPEy58M3lgXgCFjD1qWEarxQ7FIbrGe+FVzWQMEzMveYBWMtWI7nfXQrAw6D0ICvBvKqK+ZSSJ7sdJNsyQakFgLRUA7TeniSKAbt4wLwAJ1dHw7TnQQyJyHtWYLDP9Xmwga9r77DDJwmOjz+Z2Jm9T8OTUYN9HPyq0VdYkq3rzshKheugusVWLNfgYQhFEfDNjam9R7YqMfutsamwU0UOWKze05PQfjNR7Cjs8Fp+56yBuAfbrq7U0phOd9w5sWkVT1+93f8HzvPuim9P9lYq7+Obr2YJi9rnnDeC3mG93ucqz13kCaYL12PZqRv3EEt82PVuP5tzUMpoHm8SYk=
after_success: coveralls
