matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      language: python
      pytnon: "3.4"
      env: OPENTRONS_APP_UPLOAD_DIR=linux
    - os: osx
      language: python
      pytnon: "3.4"
      env: OPENTRONS_APP_UPLOAD_DIR=mac

cache:
  apt: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron
    - pip
    - $HOME/.cache/pip3
    - $HOME/.cache/our-brew

before_install:
  - ./scripts/travis.sh pre-install

install:
  - ./scripts/travis.sh install

script: echo "No python test scripts to run"

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: ot-app-builds
  skip_cleanup: true
  local-dir: releases
  upload-dir: $OPENTRONS_APP_UPLOAD_DIR
  acl: public_read
  on:
    repo: OpenTrons/opentrons-app
    all_branches: true

notifications:
  email:
    on_success: change
    on_failure: change
