sudo: false
language: python
python:
  - "3.4"
install: 
  - python setup.py install
  - pip install pylama
  - pip install coverage
  - pip install coveralls

script: 
  - nosetests --with-coverage
  - pylama

after_success:
  coveralls
