calibration:
  pipette_a:
    type: pipette_p200
    stop: 20
    drop: 25
  # Right now, calibrations are module-specific.
  # Mostly because I'm working on the old KickStarter demo bot that has
  # fancy magnetic slots and things so I can't just do a universal
  # calibration with a set microplate.
  a1:
    type: tiprack_p10
    x: 6
    y: 373
    z_grab: 70
    # Drop is super tricky.  You want it to be down far enough that 
    # gravity won't be a problem, but up high enough that it doesn't
    # grab the tip.  Also you could get it stuck on the rack if it's
    # a fancy prototype rack with multiple tiers.
    z_drop: 65
  a2:
    # This is a measurement taken with the tip rack on the end of
    # the pipette placed in the center and a smidge from the bottom
    # of well A1.
    type: microplate_96
    x: 101
    y: 373
    z: 99
  a3:
    # This calibration can be really messy, as long as it kind of
    # sort of ends up over the trash tray.
    type: trash
    x: 215
    y: 350
    z: 0

# Automating the USB serial connection process is hard. 
#
# For now, find your serial device in /dev/ somesuch or other place, chmod
# it to 666 and then add the file path here.
#
# If you're on Windows, figure out how to do USB serial connections on 
# Windows and push some new docs/code to this repo.
#
# See: https://github.com/Opentrons/pycnc/commit/a4da491b92
serial_device: 