# This is an example of a customer container definition.
#
# Two containers are specified here: 'example' (based on the filename)
# and its subset 'example.deepwell'.
#
# Dimensions are in millimeters; volumes are in microliters.

type: microplate

rows: 8
cols: 12
a1_x: 10    # X-offset of A1 from container edge
a1_y: 11    # Y-offset of A1 from container edge
spacing: 12 # Well-center to well-center spacing
diameter: 7

# Container outer dimensions
height: 150
length: 125
width: 85

# Optional; only apply to liquid containers.
volume: 100 # Maximum volume
min_vol: 50 # Minimum working volume
max_vol: 90 # Maximum working volume
well_depth: 10

subsets:
  # This container, with the default dimensions above, is available as
  # 'example.deepwell'
  deepwell:
    well_depth: 15
    spacing_y: 10
    spacing_x: 13
    subsets:
      red:
        well_depth: 25